"""Step 8: which generator, and what confidence means (Backend Plan §11.3).

    generate  -> candidate SQL + confidence
    validate  -> accept / reject
    if valid AND confidence >= threshold -> run locally   (no API call)
    else                                 -> regenerate with Gemma, validate again

Two things this module is careful about.

**Confidence decides which generator, never whether the SQL may run.** A
statement below the threshold is regenerated; a statement that fails the
validator is refused. Those are different outcomes reached by different
components, and conflating them would put a model in the safety path.

**The threshold is not guessed.** 0.55 holds until the week-9 sweep replaces
it: share-served-locally plotted against execution accuracy over the
development set, with the knee of that curve chosen. Until then every
confidence is written to `query_log` so the sweep can run over real traffic --
which is why the number is recorded even now, when there is only one
generator and nothing to escalate to.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from enum import Enum

from core.sql_generator import Candidate, Generator
from core.validator import Permitted, Verdict, validate

log = logging.getLogger("speakql.router")


class Route(str, Enum):
    LOCAL = "local"              # the primary generator was kept
    ESCALATED = "escalated"      # regenerated by the fallback
    REFUSED = "refused"          # the validator said no, both times
    CANNOT_ANSWER = "cannot_answer"   # the generator declined, honestly
    # No generator answered at all -- no checkpoint, and the LLM is down.
    # Distinct from REFUSED because nothing was refused: the interface would
    # otherwise show "the validator refused this" when the validator never ran.
    UNAVAILABLE = "unavailable"


@dataclass
class RoutingResult:
    route: Route
    candidate: Candidate | None
    verdict: Verdict | None
    attempts: list[tuple[str, float, str]] = field(default_factory=list)
    note: str = ""

    @property
    def sql(self) -> str:
        return self.candidate.sql if self.candidate else ""

    @property
    def confidence(self) -> float:
        return self.candidate.confidence if self.candidate else 0.0

    @property
    def generator(self) -> str:
        return self.candidate.generator if self.candidate else "none"

    @property
    def ok(self) -> bool:
        return self.route in (Route.LOCAL, Route.ESCALATED)


def route(
    question: str,
    schema_text: str,
    permitted: Permitted,
    *,
    primary: Generator,
    fallback: Generator | None,
    threshold: float,
) -> RoutingResult:
    """Generate, validate, and escalate once if it is worth escalating.

    Exactly one escalation. A loop that kept trying would turn a hard question
    into an expensive one and still produce nothing.
    """
    attempts: list[tuple[str, float, str]] = []

    first = _try(primary, question, schema_text)
    if first is None:
        # The primary generator is unreachable. Fall straight through rather
        # than reporting low confidence, which would be a lie about why.
        if fallback is None:
            return RoutingResult(Route.UNAVAILABLE, None, None, attempts,
                                 note="no generator is available")
        second = _try(fallback, question, schema_text)
        if second is None:
            return RoutingResult(Route.UNAVAILABLE, None, None, attempts,
                                 note="no generator is available")
        return _finish(second, permitted, Route.ESCALATED, attempts,
                       note="the primary generator was unreachable")

    if not first.sql:
        attempts.append((first.generator, 0.0, "declined"))
        return RoutingResult(Route.CANNOT_ANSWER, first, None, attempts,
                             note="the generator reported it cannot be answered "
                                  "from this schema")

    verdict = validate(first.sql, permitted)
    attempts.append((first.generator, first.confidence,
                     "accepted" if verdict.allowed else verdict.reason))

    # Good enough, and safe: keep it. No API call, no second model.
    if verdict.allowed and first.confidence >= threshold:
        return RoutingResult(Route.LOCAL, first, verdict, attempts)

    # Below the threshold, or refused. Either is a reason to ask the bigger
    # model -- a refusal often means the smaller one hallucinated a column.
    if fallback is None or fallback is primary:
        if verdict.allowed:
            # Nothing better is available, and it passed the validator. Serve
            # it, flagged, rather than refusing a safe answer for being
            # uncertain. The seal band carries the confidence.
            return RoutingResult(
                Route.LOCAL, first, verdict, attempts,
                note=f"confidence {first.confidence:.2f} is below {threshold:.2f}, "
                     "and no fallback generator is configured",
            )
        return RoutingResult(Route.REFUSED, first, verdict, attempts,
                             note=verdict.reason)

    second = _try(fallback, question, schema_text)
    if second is None or not second.sql:
        if verdict.allowed:
            return RoutingResult(Route.LOCAL, first, verdict, attempts,
                                 note="the fallback was unreachable; kept the "
                                      "local answer, which passed validation")
        return RoutingResult(Route.REFUSED, first, verdict, attempts,
                             note=verdict.reason)

    return _finish(second, permitted, Route.ESCALATED, attempts,
                   note=f"confidence {first.confidence:.2f} was below "
                        f"{threshold:.2f}" if verdict.allowed else verdict.reason)


def _finish(candidate: Candidate, permitted: Permitted, route_taken: Route,
            attempts: list, note: str) -> RoutingResult:
    """Validate the fallback's output with the SAME validator, unchanged."""
    verdict = validate(candidate.sql, permitted)
    attempts.append((candidate.generator, candidate.confidence,
                     "accepted" if verdict.allowed else verdict.reason))
    if not verdict.allowed:
        return RoutingResult(Route.REFUSED, candidate, verdict, attempts,
                             note=verdict.reason)
    return RoutingResult(route_taken, candidate, verdict, attempts, note=note)


def _try(generator: Generator, question: str, schema_text: str) -> Candidate | None:
    try:
        return generator.generate(question, schema_text)
    except NotImplementedError:
        return None            # CodeT5 before phase 5
    except Exception as exc:   # noqa: BLE001 - a dead model is not a 500
        log.warning("generator %s failed: %s", getattr(generator, "name", "?"), exc)
        return None


def is_uncertain_band(confidence: float, threshold: float, width: float = 0.08) -> bool:
    """Inside a narrow band around the threshold, ask back instead of
    answering (§11.2). Certainty just above the line is not certainty."""
    return threshold <= confidence < threshold + width
